language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
env:
  - STATIC=""
  - STATIC="--static --static-progs --no-shared"
  - DEBUG=""
  - DEBUG="--debug"
matrix:
  exclude:
    - os: osx
      env: STATIC="--static --static-progs --no-shared"
    - os: osx
      compiler: gcc
script:
  - ./waf configure --test --no-coverage --strict $DEBUG $STATIC
  - ./waf build
  - ./waf test
