language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
env:
  - FLAGS="--debug"
  - FLAGS="--debug --static --static-progs --no-shared"
  - FLAGS=""
  - FLAGS="--static --static-progs --no-shared"
script:
  - ./waf configure --test --no-coverage --strict $FLAGS
  - ./waf build
  - ./waf test
